env:
  global:
    - CC_TEST_REPORTER_ID=77b7bee3ddde517dd8962132d655935695e342de483ae9cb8d13449baf56cd30

language: python
sudo: required
python:
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - psql -c 'create database weconnect;' -U postgres

script:
  - nosetests --exe -v --with-coverage --cover-package=app


after_success:
  - coveralls
  - codecov
