language: python

env:
  DATABASE_URL_TEST="postgresql+psycopg2://postgres:@localhost:5432/testdb"
  APP_SECRET='applicationsecretkey'
  ENVIRONMENT='dev'
  EMAIL_USERNAME='weconnect.mailer'
  EMAIL_PASSWORD='emailpassword'

python:
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - psql -c 'create database testdb;' -U postgres

script:
  - nosetests --exe -v --with-coverage --cover-package=app
  
after_success:
  - coveralls
  - codecov
