language: python
python:
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - psql -c 'create database weconnect;' -U postgres

script:
  - nosetests --exe -v --with-coverage --cover-package=app

after_success:
  - coveralls
  - codecov
