env:
  global:
    - CC_TEST_REPORTER_ID=77b7bee3ddde517dd8962132d655935695e342de483ae9cb8d13449baf56cd30
    
language: python

python:
  - 3.6

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database weconnect;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build  

script:
  - nosetests --exe -v --with-coverage --cover-package=app

after_script:
  - ./cc-test-reporter after-build -t=coverage.py --exit-code $TRAVIS_TEST_RESULT

after_success:
  - coveralls
