#!/usr/bin/perl

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export PYTHONPATH=/home/andela/Documents/projects/andela/WeConnect


make venv
source ./venv/bin/activate
make install
make freeze
