#!/usr/bin/perl

export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export PYTHONPATH=$(pwd)
export ENVIRONMENT=dev

make venv
source ./venv/bin/activate
source ./LocalConfig
make install
make freeze
