"""Add business creation data

Revision ID: 3ff6fcc5b0df
Revises: 5c7e3ee18f36
Create Date: 2018-07-15 05:40:24.941533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff6fcc5b0df'
down_revision = '5c7e3ee18f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('date_created', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'date_created')
    # ### end Alembic commands ###
