"""Add review publish date

Revision ID: 712a2f61d5b0
Revises: ea6a8bac4e76
Create Date: 2018-05-19 15:12:54.012687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712a2f61d5b0'
down_revision = 'ea6a8bac4e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('publish_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'publish_date')
    # ### end Alembic commands ###
