"""drop email unique index

Revision ID: 76348e4be689
Revises: d3ad674dd190
Create Date: 2018-06-10 12:31:07.968070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76348e4be689'
down_revision = 'd3ad674dd190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    # ### end Alembic commands ###
