"""drop on update on review

Revision ID: b6756eb2183d
Revises: 76348e4be689
Create Date: 2018-07-04 08:10:31.446657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6756eb2183d'
down_revision = '76348e4be689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_review_business_id_business', 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_business_id_business'), 'review', 'business', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_review_business_id_business'), 'review', type_='foreignkey')
    op.create_foreign_key('fk_review_business_id_business', 'review', 'business', ['business_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
