"""Add review index

Revision ID: d3ad674dd190
Revises: 712a2f61d5b0
Create Date: 2018-05-19 15:27:35.631998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import func
from app.business.models import Review


# revision identifiers, used by Alembic.
revision = 'd3ad674dd190'
down_revision = '712a2f61d5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Index('ix_review_publish_date',
          Review.author_id,
          Review.business_id,
          Review.publish_date,
          func.LOWER(Review.heading),
          func.LOWER(Review.body),
          unique=True).create(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Index('ix_review_publish_date',
          Review.author_id,
          Review.business_id,
          Review.publish_date,
          func.LOWER(Review.heading),
          func.LOWER(Review.body),
          unique=True).drop(bind=op.get_bind())
    # ### end Alembic commands ###
