"""hashpassword

Revision ID: f7760f520309
Revises: 2ad03df3591d
Create Date: 2018-05-08 23:27:56.097657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7760f520309'
down_revision = '2ad03df3591d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('category', sa.String(length=127), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'category')
    # ### end Alembic commands ###
